services:
  - type: web
    name: hantakyro
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: DASH_PASSWORD
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: OWNERS
        sync: false